<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.x-breeze.test</groupId>
  <artifactId>CrossTest</artifactId>
  <properties>
  	<crosstest.version>1.0.22</crosstest.version>
  	<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <version>${crosstest.version}</version>
  <name>${project.groupId}:${project.artifactId}</name>
  <description>CrossTest is a test library for data solutions, implementing Gherkin/Cucumber.</description>
	<url>http://x-test.nl</url>	
	<licenses>
	  <license>
	    <name>The GNU General Public License, Version 3</name>
	    <url>https://www.gnu.org/licenses/gpl-3.0.html</url>
	  </license>
	</licenses>
	<developers>
	    <developer>
	      <name>Willem Otten</name>
	      <email>Willem@x-breeze.com</email>
	      <organization>CrossBreeze</organization>
	      <organizationUrl>http://x-breeze.com</organizationUrl>
	    </developer>
	    <developer>
	      <name>Harmen Wessels</name>
	      <email>Harmen@x-breeze.com</email>
	      <organization>CrossBreeze</organization>
	      <organizationUrl>http://x-breeze.com</organizationUrl>
	    </developer>
	    <developer>
	      <name>Jacob Siemaszko</name>
	      <email>Jacob@x-breeze.com</email>
	      <organization>CrossBreeze</organization>
	      <organizationUrl>http://x-breeze.com</organizationUrl>
	    </developer>
  	</developers>
  	<scm>
	  <connection>https://dev.azure.com/x-breeze/CrossTest_Community_Edition/_git/CrossTest_CE_Java_Cucumber</connection>
	  <developerConnection>https://dev.azure.com/x-breeze/CrossTest_Community_Edition/_git/CrossTest_CE_Java_Cucumber</developerConnection>
	  <url>https://dev.azure.com/x-breeze/CrossTest_Community_Edition/_git/CrossTest_CE_Java_Cucumber</url>
	</scm>
	<distributionManagement>
	  <snapshotRepository>
	    <id>ossrh</id>
	    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
	  </snapshotRepository>
	  <repository>
	    <id>ossrh</id>
	    <url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
	  </repository>
	</distributionManagement>
  <dependencies>
  		<dependency>
			<groupId>com.x-breeze.test</groupId>
			<artifactId>CrossTestCore</artifactId>
			<version>${crosstest.version}</version>
		</dependency>		
  </dependencies>
  <profiles>
		<profile>			
			<id>release</id>
				<build>
					<plugins>
						<plugin>
						<!--  build jar file with sources (Sonatype requirement) -->
						  <groupId>org.apache.maven.plugins</groupId>
						  <artifactId>maven-source-plugin</artifactId>
						  <executions>
						    <execution>
						      <id>attach-sources</id>
						      <goals>
						        <goal>jar</goal>
						      </goals>
						    </execution>
						  </executions>
						</plugin>
					<plugin>
						<!--  Build jar file with javadocs (Sonatype requirement) -->
					  <groupId>org.apache.maven.plugins</groupId>
					  <artifactId>maven-javadoc-plugin</artifactId>
					  <configuration>
				          <show>protected</show>
				          <failOnError>false</failOnError>
				          <source>1.8</source>
			          </configuration>
					  <executions>
					    <execution>
					      <id>attach-javadocs</id>
					      <goals>
					        <goal>jar</goal>
					      </goals>
					    </execution>
					  </executions>
					</plugin>		 
				    <plugin>
				    	<!--  Sign artifacts with gpg (Sonatype requirement) -->
				      <groupId>org.apache.maven.plugins</groupId>
				      <artifactId>maven-gpg-plugin</artifactId>
				      <version>3.0.1</version>
				      <executions>
				        <execution>
				          <id>sign-artifacts</id>
				          <phase>verify</phase>
				          <goals>
				            <goal>sign</goal>
				          </goals>
				        </execution>
				      </executions>
				    </plugin>
					 <plugin>
						<groupId>org.sonatype.central</groupId>
						<artifactId>central-publishing-maven-plugin</artifactId>
						<version>0.9.0</version>
						<extensions>true</extensions>
						<configuration>
							<publishingServerId>central</publishingServerId>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>		
	</profiles>
	<build>
		<sourceDirectory>src/main/java</sourceDirectory>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.10.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>