# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
      include:
      - master
      - develop
      - features/*
      - hotfix/*

  paths:
      include:
      - ./CrossTest_Java
      - ./Generation
      - ./Java
      - ./Model
      - ./Old

pool:
  vmImage: 'ubuntu-latest'


stages:
- stage: Check
  jobs:
    - job: CheckCode
      displayName: Check code
      steps:
      - task: Maven@3
        inputs:
          mavenPomFile: '$(System.DefaultWorkingDirectory)/**/pom.xml'
          goals: 'validate'
          publishJUnitResults: true
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          mavenVersionOption: 'Default'
          mavenOptions: '-Xmx3072m'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false

- stage: Package
  jobs:
    - job: PackageCode
      displayName: Package code
      steps:
      - task: Maven@3
        inputs:
          mavenPomFile: '$(System.DefaultWorkingDirectory)/**/pom.xml'
          goals: 'package'
          publishJUnitResults: true
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          mavenVersionOption: 'Default'
          mavenOptions: '-Xmx3072m'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false

    - job: TestCode
      displayName: Test code
      steps:
      - task: Maven@3
        inputs:
          mavenPomFile: '$(System.DefaultWorkingDirectory)/TestCrossTest/pom.xml'
          goals: 'test'
          publishJUnitResults: true
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          mavenVersionOption: 'Default'
          mavenOptions: '-Xmx3072m'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
