# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
      include:
      - master
      - develop
      - features/*
      - hotfix/*

  paths:
      include:
      - ./CrossTest_Java
      - ./Generation
      - ./Java
      - ./Model
      - ./Old

pool:
  vmImage: 'ubuntu-latest'


stages:
- stage: Check
  jobs:
    - job: CheckCode
      displayName: Check code
      steps:
      - task: Maven@3
        inputs:
          mavenPomFile: './Crosstest_Java/CrossTest/pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: 'true'
          goals: 'spotbugs:check'
- stage: Package
  jobs:
    - job: PackageCode
      displayName: Package code
      steps:
      - task: Maven@3
        inputs:
          mavenPomFile: './Crosstest_Java/CrossTest/pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          goals: 'package'
