# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
      include:
      - master
      - develop
      - features/*
      - hotfix/*

  paths:
      include:
      - ./CrossTest_Java
      - ./Generation
      - ./Java
      - ./Model
      - ./Old

jobs:
  - job: CheckCode
    displayName: Check code
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    
    - task: PowerShell@2
      inputs:
        filePath: '$(System.DefaultWorkingDirectory)/TestCrossTest/start_xtestsqlserver.ps1'

    - task: Maven@3
      inputs:
        mavenPomFile: '$(System.DefaultWorkingDirectory)/CucumberDataComparison/pom.xml'
        goals: 'install'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false


    - task: Maven@3
      inputs:
        mavenPomFile: '$(System.DefaultWorkingDirectory)/CrossTest/pom.xml'
        goals: 'install'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - task: Maven@3
      inputs:
        mavenPomFile: '$(System.DefaultWorkingDirectory)/CrossTestSteps/pom.xml'
        goals: 'install'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - task: Maven@3
      inputs:
        mavenPomFile: '$(System.DefaultWorkingDirectory)/InformaticaPowerCenter/pom.xml'
        goals: 'install'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
      
    - task: Maven@3
      inputs:
        mavenPomFile: '$(System.DefaultWorkingDirectory)/TeradataCustomDataTypes/pom.xml'
        goals: 'install'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - task: Maven@3
      inputs:
        mavenPomFile: '$(System.DefaultWorkingDirectory)/TestCrossTest/pom.xml'
        goals: 'test'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        mavenVersionOption: 'Default'
        mavenOptions: '-Xmx3072m'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

#     - task: Maven@3
#       inputs:
#         mavenPomFile: '$(System.DefaultWorkingDirectory)/TestCrossTest/pom.xml'
#         goals: 'package'
#         publishJUnitResults: false
#         javaHomeOption: 'JDKVersion'
#         jdkVersionOption: '1.8'
#         mavenVersionOption: 'Default'
#         mavenOptions: '-Xmx3072m'
#         mavenAuthenticateFeed: false
#         effectivePomSkip: false
#         sonarQubeRunAnalysis: false
# #        options: '-DskipTests=true' 

    # - task: PublishPipelineArtifact@1
    #   inputs:
    #     targetPath: '$(System.DefaultWorkingDirectory)'
    #     artifact: '$(Build.DefinitionName)'
    #     publishLocation: 'pipeline'
