<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.xbreeze.xtest</groupId>
    <artifactId>Crosstest_Java_Cucumber</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>CrossTest</module>
        <module>CrossTestSteps</module>
        <module>CucumberDataComparison</module>
        <module>CucumberRunner</module>
        <module>Execution/InformaticaPowerCenter</module>
        <module>TeradataCustomDataTypes</module>
        <module>TestCrossTest</module>
    </modules>
    <name>Crosstest Java Cucumber Parent</name>
    <description>Parent POM for all Crosstest Java Cucumber modules</description>
</project>
